version: "3.8"
services:
    db:
        image: yobasystems/alpine-mariadb:10.4.17
        container_name: db_myagenda
        restart: no
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: myagenda123
        ports:
            - '3306:3306'
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: